# -*- coding: utf-8 -*-
"""ENG220.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHt1s7kMq6XCbS7WLQhXkjLTmA0DmevN
"""

import streamlit as st
import pandas as pd

# Title of the app
st.title('Interactive Censorship Data Visualization App')

# File uploader for the CSV file
uploaded_file = st.file_uploader("Book2.csv", type=["csv"])

if uploaded_file is not None:
    # Load the uploaded CSV file into a DataFrame
    df = pd.read_csv(uploaded_file)

    # Display the dataset
    st.write("Sales Data:")
    st.write(df)

    # Let the user select columns for the chart
    columns = df.columns.tolist()

    # Dropdowns for X and Y axes selection
    x_axis = st.selectbox('Select column for X-axis', columns)
    y_axis = st.selectbox('Select column for Y-axis', columns)

    # Choose chart type: Bar Chart or Line Chart
    chart_type = st.selectbox('Select chart type', ['Bar Chart', 'Line Chart'])

    # Display chart based on user selections
    if chart_type == 'Bar Chart':
        st.bar_chart(df[[x_axis, y_axis]].set_index(x_axis))
    elif chart_type == 'Line Chart':
        st.line_chart(df[[x_axis, y_axis]].set_index(x_axis))
else:
    st.write("Please upload a CSV file to proceed.")