# -*- coding: utf-8 -*-
"""Unten1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xjUnmVX3y1JNN3FEEwvceFnY-6L9lkI
"""

pip install streamlit pandas matplotlib

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title and description
st.title("Dashboard Example")
st.write("This is a simple Streamlit dashboard.")

# Upload a file
uploaded_file = st.file_uploader("Book2.csv", type="csv")
if uploaded_file:
    data = pd.read_csv(uploaded_file)
    st.write("Data Preview:", data.head())

    # Plot data if numeric
    numeric_columns = data.select_dtypes(['number']).columns
    if not numeric_columns.empty:
        st.write("Select columns to plot:")
        x_col = st.selectbox("X-Axis", numeric_columns)
        y_col = st.selectbox("Y-Axis", numeric_columns)
        if x_col and y_col:
            fig, ax = plt.subplots()
            ax.scatter(data[x_col], data[y_col])
            ax.set_title(f"{x_col} vs {y_col}")
            ax.set_xlabel(x_col)
            ax.set_ylabel(y_col)
            st.pyplot(fig)

# Add interactivity
if st.button("Click me!"):
    st.write("Button clicked!")