# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1603vV61hrct0xejBOlNJwdKQYohOr-5M
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Title of the Dashboard
st.title("Simple Dashboard Example")

# Creating a sample dataset
data = {
    "Date": pd.date_range(start="2024-01-01", periods=30, freq="D"),
    "Sales": np.random.randint(100, 500, size=30),
    "Expenses": np.random.randint(50, 300, size=30),
}
df = pd.DataFrame(data)

# Display the dataset
st.subheader("Data Overview")
st.dataframe(df)

# Line chart for Sales and Expenses
st.subheader("Sales and Expenses Over Time")
fig, ax = plt.subplots()
ax.plot(df["Date"], df["Sales"], label="Sales", marker='o')
ax.plot(df["Date"], df["Expenses"], label="Expenses", marker='o')
ax.set_title("Sales vs Expenses")
ax.set_xlabel("Date")
ax.set_ylabel("Amount")
ax.legend()
st.pyplot(fig)

# Bar chart for total Sales and Expenses
st.subheader("Total Sales and Expenses")
total_sales = df["Sales"].sum()
total_expenses = df["Expenses"].sum()

# Add a slider to select a date range
st.subheader("Select Date Range")
start_date = st.date_input("Start Date", df["Date"].min())
end_date = st.date_input("End Date", df["Date"].max())
filtered_data = df[(df["Date"] >= pd.to_datetime(start_date)) & (df["Date"] <= pd.to_datetime(end_date))]

# Display filtered data
st.write("Filtered Data:")
st.dataframe(filtered_data)

# Show summary statistics
st.subheader("Summary Statistics")
st.write(filtered_data.describe())

# Run the Streamlit app
if __name__ == "__main__":
    st.write("You can run this dashboard with the command: streamlit run <filename>.py")