# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1603vV61hrct0xejBOlNJwdKQYohOr-5M
"""

# Import necessary libraries
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Title of the dashboard
st.title("Streamlit Dashboard Example")

# Generate some sample data
data = {
    "Date": pd.date_range(start="2024-01-01", periods=30, freq="D"),
    "Sales": np.random.randint(100, 500, size=30),
    "Expenses": np.random.randint(50, 300, size=30),
}
df = pd.DataFrame(data)

# Display the dataset
st.subheader("Dataset")
st.dataframe(df)

# Plot Sales and Expenses over Time
st.subheader("Sales and Expenses Over Time")
fig, ax = plt.subplots()
ax.plot(df["Date"], df["Sales"], label="Sales", marker='o')
ax.plot(df["Date"], df["Expenses"], label="Expenses", marker='o')
ax.set_xlabel("Date")
ax.set_ylabel("Amount")
ax.legend()
st.pyplot(fig)

# Plot Total Sales and Expenses as Bar Chart
st.subheader("Total Sales and Expenses")
total_sales = df["Sales"].sum()
total_expenses = df["Expenses"].sum()
fig, ax = plt.subplots()
ax.bar(["Total Sales", "Total Expenses"], [total_sales, total_expenses], color=["blue", "orange"])
ax.set_ylabel("Amount")
st.pyplot(fig)

# Add Date Range Filter
st.subheader("Filter Data by Date Range")
start_date = st.date_input("Start Date", df["Date"].min())
end_date = st.date_input("End Date", df["Date"].max())
filtered_data = df[(df["Date"] >= pd.to_datetime(start_date)) & (df["Date"] <= pd.to_datetime(end_date))]

# Display Filtered Data
st.write("Filtered Data:")
st.dataframe(filtered_data)

# Summary statistics
st.subheader("Summary Statistics")
st.write(filtered_data.describe())